version: '2'
services:
    nginx:
      build: ./nginx
      links:
        - flask
      ports:
        - "80:80"
      restart: always
 
    mysql:
      image: daocloud.io/mysql:5.6
      environment:
        - MYSQL_ROOT_PASSWORD=root123
        - MYSQL_DATABASE=test
      volumes:
        - /data/mysql:/var/lib/mysql
      ports:
        - "3306:3306"
        
    flask:
      build: ./flask
      ports:
        - "5000:5000"
      volumes:
        - .:/code
      expose:
        - "5000"
    